#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


#npm run build:prod
#npm run lint:ts:fix
#npm run lint:scss:fix
#npm run test:unit
#npm run storybook:build
#npm run test:ui

#проверка линтом только измененные файлы
#npm run lint-staged

